[project]
name = "flask-cloud-api-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.5"
dependencies = [
    "anthropic>=0.66.0",
    "datamodel-code-generator>=0.28.2",
    "flask==3.1.0",
    "flask-cors==5.0.0",
    "flask-restful==0.3.10",
    "gunicorn==23.0.0",
    "langchain>=0.3.20",
    "langchain-aws>=0.2.35",
    "langchain-core>=0.3.41",
    "langchain-google-vertexai>=2.0.14",
    "langchain-mcp-adapters>=0.1.0",
    "langchain-openai>=0.3.35",
    "openai>=2.7.1",
]

[tool.uv]
exclude-newer = "7 days"
python-preference = "only-system"
