apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flask-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "flask-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flask-api.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "flask-api.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
